### ISSUE TITLE
Error generating target in getRequests

### ISSUE THREAD

**Issue by RedStoner** [uecasm/colony4cc#10]
This is spamming the console quite hard and in game, getRequests errors out due to the target being nil. I have written code to keep the program running, but the owner of the server hates the console spam.
![image](https://user-images.githubusercontent.com/1278466/134490274-5a7b3919-04a3-43c1-993c-da4717b8f05d.png)

versions -
Colony4ComputerCraft-1.16.5-1.4.0
cc-tweaked-1.16.5-1.98.2
minecolonies-1.0.0-RELEASE-universal
structurize-0.13.219-ALPHA-universal

**Comment by uecasm** [comment]
Can you show me some example data where this is happening and the target returns nil?  As far as I am aware, that should never happen.

**Comment by RedStoner** [comment]
*edit - Ignore this... i am just dumb.
I wrote the wrong command up top there. Using getBuilderResources. Sorry. Read the console log and it stuck in head.
It just errors. I cant retrieve the data as the function never passes through fully... 
![image](https://user-images.githubusercontent.com/1278466/134591459-b999c9b1-90d6-45c3-ae38-c5b776ebbc25.png)
I have tried this on many colonies on the server, and i get the same error. in my code i just check if it is returning nil, if so, i ignore that processing tick.

**Comment by RedStoner** [comment]
So, just got new info... not sure how to handle it. being told by server owner the console is not spamming anymore. This was an issue we had the other day before and we did a small update on the pack. The console spam is gone, and I put code in my program to print out the requests on a fail, and over 30 mins of code running, no target error. I am calling getRequests in my code and it seems to be working. Realizing what the error above was (me being dumb and not passing coords). I think this issue is closed.
