### ISSUE TITLE
Incorrect ID on Pixie Dust research

### ISSUE THREAD

**Issue by RedStoner** [uecasm/colony4cc#11]
![image](https://user-images.githubusercontent.com/1278466/134760718-946ab669-d2fa-4601-afa7-cb42562ecf80.png)
Solar Holography and Pixie dust share the same ID. I believe this to be a mistake as id's typically are unique.

versions -
Colony4ComputerCraft-1.16.5-1.4.0
cc-tweaked-1.16.5-1.98.2
minecolonies-1.0.0-RELEASE-universal
structurize-0.13.219-ALPHA-universal

**Comment by uecasm** [comment]
That's really weird, since the only place the id should be coming from is the filename, which obviously must be (and is) unique. 
 And I can't reproduce this in a test world:

```
    {
      name = "More Scrolls",
      id = "minecolonies:technology/morescrolls",
      status = "NOT_STARTED",
      children = {
        {
          id = "colony4cc:pixie_dust",
          status = "NOT_STARTED",
          name = "Pixie Dust",
          effects = {
            "Dust Shaker",
          },
        },
      },
      effects = {
        "Enchanter Learns Scroll Recipes to Locate Workers and Summon Guards",
      },
    },
```

```
            {
              name = "Improved Holography",
              id = "colony4cc:improved_holography",
              status = "FINISHED",
              children = {
                {
                  id = "colony4cc:solar_holography",
                  status = "FINISHED",
                  name = "Solar Holography",
                  effects = {
                    "Solar Panels",
                  },
                },
              },
              effects = {
                "RGB Charge Improvement",
              },
            },
```

Although looking at that now I'm wondering if I should provide more detail on the effects.

**Comment by RedStoner** [comment]
server restarted last night. Its returning the correct stuff now. This is annoying when i get these random bugs i can only replicate once. WTF. Want me to close this one or leave it?
