### ISSUE TITLE
1.17.1 Can't find Computer Craft, ignores CC-Tweaked

### ISSUE THREAD

**Issue by kreezxil** [uecasm/colony4cc#13]
client crash: https://gist.github.com/eb39e0afcdc12c8ca182b7c8a4891af6
client log: https://gist.github.com/d8adcf1571892fa221c31b63e63313b0\
client debug: https://gist.github.com/679151058654585be2bdb33c59e3b75f

Forge: 1.17.1-37.0.126
Mod: 1.17.1-2.0.0

Pack Export: https://drive.google.com/file/d/18kPhNdv7fmUYvyiFUioDUt3o64o4SJu0/view?usp=drivesdk

**Comment by uecasm** [comment]
For the moment, you'll need to downgrade to CC:Tweaked 0.98.  They've changed the API on me -- not a bad change, but not supported yet.  I'll look into it.

**Comment by uecasm** [comment]
Should be fixed in 2.1.0
