### ISSUE TITLE
Block is transparent causing you to see thru the block.

### ISSUE THREAD

**Issue by AzPure** [uecasm/colony4cc#18]
**Describe the bug**
'The Colony Peripheral' is see-through, not sure how this happens.

**To Reproduce**
1. Installed on ALL THE MODS 7 modpack (as an additional mod added afterwards)
2. Place block.
3. Observe through-block.

**Expected behavior**
No see-though expected!

**Screenshots**
![image](https://user-images.githubusercontent.com/24412690/182567438-53899ba9-f80a-4157-817e-d491d69f6863.png)

**Versions:**
 - Minecraft: 1.16.2
 - Minecolonies: 1.0.893-ALPHA
 - Colony4cc: 2.2.1

**Additional context**
No logs from the server complaining about the issue that I can see.

**Comment by uecasm** [comment]
Did you mean 1.18.2?  1.16.2 is not supported, and that looks like a 1.18.2 version of minecolonies.

**Comment by uecasm** [comment]
Thanks for the report.  This is fixed in version 2.2.2.
