### ISSUE TITLE
Server Crashed while using getInfo()

### ISSUE THREAD

**Issue by PhamKun** [uecasm/colony4cc#19]
**Describe the bug**
- I go to lua, type colony.getInfo(), the game crashed with error 
Error: java.lang.NoSuchMethodError: 'java.lang.String com.minecolonies.api.colony.IColony.getStyle()'

**To Reproduce**
1. place down townhall and setup colonies peripherals with a cc computer
2. create new town
3. turn on cc computer, lua, and try colony.getInfo()
4. the game/server shutdown

**Expected behavior**
should give out the info of the colony

**Screenshots**

**Versions:**
 - Minecraft: 1.19.1, forge 42.0.9
 - Minecolonies: 1.19.2-1.0.
 - Colony4cc: 1.19.1-2.3.0.jar

**Additional context**
Include logs (from a paste site like [gist](https://gist.github.com/)) if appropriate.
[crash-2022-09-11_22.43.15-server.txt](https://github.com/uecasm/colony4cc/files/9544406/crash-2022-09-11_22.43.15-server.txt)

**Comment by PhamKun** [comment]
I

**Comment by PhamKun** [comment]
Minecraft: 1.19.2, forge 43.1.16
Minecolonies: 1.19.2-1.0.1004-ALPHA
Colony4cc: 1.19.1-2.3.0.jar

I also tried 1.19.2. Info are above, same thing

**Comment by uecasm** [comment]
Ah, this will be due to the new build tool changes.  I thought I'd protected most of the API calls for unexpected changes, but I guess this one was extra unexpected.

**Comment by PhamKun** [comment]
lol. There also crashed with getBuildings. I havent tested the citizen info so idk if it will crash or not

**Comment by uecasm** [comment]
It should only be those two.  This is fixed in version 2.3.1, which should be out in a few minutes.
