### ISSUE TITLE
[1.20.1] Unable to Request RGB Charge from Postbox

### ISSUE THREAD

**Issue by Reveter** [uecasm/colony4cc#25]
**Describe the bug**
Unable to request RGB Charge at Minecolonies postbox

**To Reproduce**
1. Place down Postbox
2. Search RGB Charge
4. Nothing Comes up

**Expected behavior**
Colony4cc items to be requestable by postbox, especially since the RGB Charge is only craftable by Blacksmiths and Mechanics.

**Screenshots**
![image](https://github.com/uecasm/colony4cc/assets/8112174/0f807048-4a86-4e3a-a466-5882502b9ac3)

**Versions:**
 - Minecraft: 1.20.1
 - Minecolonies: 1.20.1-1.1.240-RELEASE
 - Colony4cc: 1.20.1-2.6.0

**Comment by uecasm** [comment]
Thanks for the report.  This actually looks like a bug in MineColonies itself; no need to report it there, I'll take a look at it.

In the meantime, you can work around this by exiting back to the title screen and then loading back into the world without restarting Minecraft.

**Comment by uecasm** [comment]
Try it with minecolonies-1.20.1-1.1.268-BETA or above.
