### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by ghost** [uecasm/colony4cc#26]
**Describe the bug**
Whem Supplementaries and Alexis Caves installed game crash on world load/creation.

**To Reproduce**
install mods:
![image](https://github.com/uecasm/colony4cc/assets/146892171/07bb47b5-64ec-4ccc-9d67-13f668a8f521)
boot minecraft
create new world

**Expected behavior**
World load

**Actual behavior**
MInecraft crash

**Logs**
[latest.log](https://github.com/uecasm/colony4cc/files/13527002/latest.log)
[crash-2023-12-01_15.17.08-server.txt](https://github.com/uecasm/colony4cc/files/13527000/crash-2023-12-01_15.17.08-server.txt)

**Comment by uecasm** [comment]
This looks like an issue with Supplementaries not liking something related to banners.  This mod doesn't have anything to do with banners, so you will need to investigate elsewhere.

**Comment by MehVahdJukaar** [comment]
Issue is from this mod.read the log explains it all, forge logs the error too. You are loading sheet class too early

**Comment by uecasm** [comment]
Thanks for the report; I see the problem now.  2.6.1 (out shortly) should fix it.
