### ISSUE TITLE
Counts are all 1

### ISSUE THREAD

**Issue by RedStoner** [uecasm/colony4cc#3]
Trying to get the amount of materials needed using colony.getBuilderResources(). I am only getting a value of 1 for all items in the resource list using the .count value. When I check the builders table itself, it is clearly  not a value of 1 on all of them. 

Section of code im trying to use: [https://pastebin.com/CqmD8mjF]
I have several commented out debug lines in there where I was testing. I just cannot seem to find the proper value for count.

**Comment by RedStoner** [comment]
I have tried formatting the code on the page, but i cant seem to get it to view correct, going to put in the pastebin for it instead.

**Comment by uecasm** [comment]
Fixed in 1.2.3.
