### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by Devilswarchild** [uecasm/colony4cc#30]
Had reported this to cc:tweaked devs and they informed me that is was an issue on your mods end.

https://github.com/cc-tweaked/CC-Tweaked/issues/1921

### Minecraft Version

1.20.1

### Version

2.6.3

### Details

[Crash report ](https://mclo.gs/dSySXNN)

[Latest Log](https://mclo.gs/7jNJ8fx)

[Debug Log](https://mclo.gs/jS15kmj)

[My Modpack](https://www.curseforge.com/minecraft/modpacks/minecolonies-dimensional-adventure)

steps:

update cc tweaked to latest in and launch the game

expected behavior: Not to crash.

**Comment by uecasm** [comment]
Thanks for the report.  This is fixed in 2.6.4, which should be available shortly.
