### ISSUE TITLE
Mod crashes on 1.20.1 Minecolonies latest update

### ISSUE THREAD

**Issue by ModernGamingWorld** [uecasm/colony4cc#31]
Mod ID: 'minecolonies', Requested by: 'colony4cc', Expected range: '[1.20.1-1.1.464-RELEASE,)', Actual version: '1.1.636-1.20.1-beta'

**Comment by uecasm** [comment]
Minecolonies broke their versioning format.  I've been arguing with them about changing it back to unbreak things.  In the meantime, you can downgrade to a version that has the MC version number first and then it will work again.

**Comment by uecasm** [comment]
Minecolonies has switched back to the original version format, so this should be resolved when upgrading to minecolonies-1.20.1-1.1.644 or later.
