### ISSUE TITLE
getCitizens Throwing NPE

### ISSUE THREAD

**Issue by RedStoner** [uecasm/colony4cc#5]
Havn't had a chance to play with the new health stats as I have been getting a null pointer exception when calling colony.getCitizens(). Terminal displays: 
'colonyInfo.lua:26: Java Exception Thrown: java.lang.NullPointerException: null key in entry:null=net.minecraft.util.Tuple@69738c21'

The code on line 26 is just a call to that function

citizens = colony.getCitizens()

Mod Versions:
  Minecolonies - 0.14.201-BETA
  MineColonies for ComputerCraft - 1.2.3 (first noticed issue on 1.2.4)
  Structurize 0.13.175-alpha
Forge version: 36.1.0

**Comment by RedStoner** [comment]
Ok... Seems it may not have to do with the newest version. I downgraded version, and was on that for a couple hours before I got pretty much the same error. Only difference is - Tuple@5a733841
I wonder if this is a minecolonies issue and not this mod in particular. 
Updating original post with versions of the mods as well.

**Comment by uecasm** [comment]
Is this on single player or on server?  Is it possible that some of your colony is getting unloaded?

Having said that, in theory all the data should be available all the time, except for the newly-added health etc which does require the citizen to be in a loaded chunk (but will just quietly disappear from the results when that's not the case).

You said that it seems to be intermittent, any other ideas what might be triggering it?  Does it always break after a certain amount of time, or when you disconnect/reconnect to a server, or something else perhaps?

If you can figure out a trigger, you can try running `/mc colony export 1` (replace 1 with your actual colony id if different), which will make a special backup of your colony data; if you send that to me then I could try to reproduce the problem on a copy of your colony, in case it's something specific to something in there.

**Comment by uecasm** [comment]
I've just uploaded 1.2.5, which contains a workaround for the only thing that it seems like it could possibly be -- it should now work, but one or more citizens might be missing their skill data (since it appears that is where the invalid data was).  I'm still interested in getting your colony data if you can figure out how to trigger it, to see if that's something that can be fixed on the mcol side.

**Comment by RedStoner** [comment]
Single player. I think it has to do with manually assigning builders to a building. I was trying to construct a building that was a bit out of range for the builder. When queued the builder seems to have both jobs assigned to it. Attaching export 
[colony1Export.zip](https://github.com/uecasm/colony4cc/files/6634194/colony1Export.zip)

**Comment by RedStoner** [comment]
I have not seen this happen again since updating. The problem seems to have been resolved.

**Comment by RedStoner** [comment]
Much time with code running. No issues. Will say this has been fixed.
